rconsolename('Dino Hud Crack')
rconsoleclear()
rconsoleinfo("Dino Hud Crack")
rconsoleinfo("https://dinohud.netlify.app")
rconsoleinfo("Crack:L9Der")
wait(1)
rconsoleprint(" " .. " \n")
rconsolewarn("Scanning user on the system!")
wait(0.50)
rconsoleinfo("ID Server:" .. (math.random(100000000, 999999999)))
rconsoleinfo("Rank:Infinity | Expired:Forever")
rconsolewarn("Thanks for joining (Dino-Hud)")
rconsoleprint(" " .. " \n")
wait(0.50)
rconsolewarn("Scanning Game on the system!")
wait(0.50)
loadstring(game:HttpGetAsync(("https://raw.githubusercontent.com/hovuongphu/Dino-Hud/main/System/Load%20Game.lua")))()