rconsolename('Dino Hud')
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V1.3.5" .. " \n")
rconsoleprint(" " .. " \n")
wait(1)
rconsoleprint("Game Coding." .. " \n")
wait(1.70)
rconsoleprint("Load File Game." .. " \n")
wait(1.70)
rconsoleprint("Load File Anti-Cheat." .. " \n")
wait(1.70)
rconsoleprint("Load File Dino Hud." .. " \n")
wait(1.70)
rconsoleprint("Loading.." .. " \n")
wait(2.99)
rconsoleprint("Complete." .. " \n")
loadstring(game:HttpGetAsync(("https://raw.githubusercontent.com/hovuongphu/Dino-Hud/main/laucher/introl.lua")))()