rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-CheatV3." .. " \n")
wait(0.55)
rconsoleprint(" " .. " \n")
rconsoleprint("System." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Check Game|Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Anti-Cheat of the game |Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Use Script|Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Low Safety|Not Safe." .. " \n")
wait(0.25)
rconsoleprint(" " .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Loading." .. " \n")
rconsoleprint("Check Game." .. " \n")
rconsoleprint("@@CYAN@@")
wait(1.20)
rconsoleprint("1|100%." .. " \n")
wait(0.20)
rconsoleprint("28|100%." .. " \n")
wait(0.20)
rconsoleprint("35|100%." .. " \n")
wait(0.20)
rconsoleprint("52|100%." .. " \n")
wait(0.20)
rconsoleprint("68|100%." .. " \n")
wait(0.20)
rconsoleprint("82|100%." .. " \n")
wait(0.20)
rconsoleprint("94|100%." .. " \n")
wait(0.20)
rconsoleprint("100|100%." .. " \n")
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-CheatV3." .. " \n")
wait(0.20)
rconsoleprint(" " .. " \n")
rconsoleprint("System." .. " \n")
rconsoleprint("Check Game|Safe." .. " \n")
wait(0.25)
rconsoleprint("@@RED@@")
rconsoleprint("Anti-Cheat of the game |Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Use Script|Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Low Safety|Not Safe." .. " \n")
--//load------------------------------------------------------------------------------
wait(0.25)
rconsoleprint(" " .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Loading." .. " \n")
rconsoleprint("Check Anti-Cheat of the game." .. " \n")
rconsoleprint("@@CYAN@@")
wait(1.20)
rconsoleprint("1|100%." .. " \n")
wait(0.20)
rconsoleprint("60|100%." .. " \n")
wait(0.20)
rconsoleprint("81|100%." .. " \n")
wait(0.20)
rconsoleprint("96|100%." .. " \n")
wait(0.20)
rconsoleprint("100|100%." .. " \n")
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-CheatV3." .. " \n")
wait(0.20)
rconsoleprint(" " .. " \n")
rconsoleprint("System." .. " \n")
rconsoleprint("Check Game|Safe." .. " \n")
wait(0.25)
rconsoleprint("Anti-Cheat of the game |Safe." .. " \n")
wait(0.25)
rconsoleprint("@@RED@@")
rconsoleprint("Use Script|Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Low Safety|Not Safe." .. " \n")
--..............................................................................
wait(0.25)
rconsoleprint(" " .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Loading." .. " \n")
rconsoleprint("Check Use Script." .. " \n")
rconsoleprint("@@CYAN@@")
wait(1.20)
rconsoleprint("1|100%." .. " \n")
wait(0.20)
rconsoleprint("45|100%." .. " \n")
wait(0.20)
rconsoleprint("57|100%." .. " \n")
wait(0.20)
rconsoleprint("62|100%." .. " \n")
wait(0.20)
rconsoleprint("79|100%." .. " \n")
wait(0.20)
rconsoleprint("97|100%." .. " \n")
wait(0.20)
rconsoleprint("100|100%." .. " \n")
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-CheatV3." .. " \n")
wait(0.20)
rconsoleprint(" " .. " \n")
rconsoleprint("System." .. " \n")
rconsoleprint("Check Game|Safe." .. " \n")
wait(0.25)
rconsoleprint("Anti-Cheat of the game |Safe." .. " \n")
wait(0.25)
rconsoleprint("Use Script|Safe." .. " \n")
wait(0.25)
rconsoleprint("@@RED@@")
rconsoleprint("Low Safety|Not Safe." .. " \n")
--..............................................................................
wait(0.25)
rconsoleprint(" " .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Loading." .. " \n")
rconsoleprint("Check Low Safety." .. " \n")
rconsoleprint("@@CYAN@@")
wait(1.20)
rconsoleprint("1|100%." .. " \n")
wait(0.20)
rconsoleprint("36|100%." .. " \n")
wait(0.20)
rconsoleprint("75|100%." .. " \n")
wait(0.20)
rconsoleprint("97|100%." .. " \n")
wait(0.20)
rconsoleprint("100|100%." .. " \n")
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-CheatV3." .. " \n")
wait(0.20)
rconsoleprint(" " .. " \n")
rconsoleprint("System." .. " \n")
rconsoleprint("Check Game|Safe." .. " \n")
wait(0.25)
rconsoleprint("Anti-Cheat of the game |Safe." .. " \n")
wait(0.25)
rconsoleprint("Use Script|Safe." .. " \n")
wait(0.25)
rconsoleprint("Low Safety|Safe." .. " \n")
rconsoleprint(" " .. " \n")
wait(0.25)
rconsoleprint("Load Dino-Hud." .. " \n")
wait(0.10)
loadstring(game:HttpGetAsync(("https://raw.githubusercontent.com/hovuongphu/Dino-Hud/main/laucher/introl.lua")))()