rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
game.Players.LocalPlayer:Kick("  Dino hud server stopped working due to maintenance and Update")
--[[
rconsoleprint("Anti-CheatV3." .. " \n")
wait(0.55)
rconsoleprint(" " .. " \n")
rconsoleprint("System." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Check Game|Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Anti-Cheat of the game |Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Use Script|Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Perating Server|Offline." .. " \n")
wait(0.25)
rconsoleprint(" " .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Loading." .. " \n")
rconsoleprint("Check Game." .. " \n")
rconsoleprint("@@CYAN@@")
wait(1.20)
rconsoleprint("1|100%." .. " \n")
wait(0.20)
rconsoleprint("28|100%." .. " \n")
wait(0.20)
rconsoleprint("35|100%." .. " \n")
wait(0.20)
rconsoleprint("52|100%." .. " \n")
wait(0.20)
rconsoleprint("68|100%." .. " \n")
wait(0.20)
rconsoleprint("82|100%." .. " \n")
wait(0.20)
rconsoleprint("94|100%." .. " \n")
wait(0.20)
rconsoleprint("100|100%." .. " \n")
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-CheatV3." .. " \n")
wait(0.20)
rconsoleprint(" " .. " \n")
rconsoleprint("System." .. " \n")
rconsoleprint("Check Game|Safe." .. " \n")
wait(0.25)
rconsoleprint("@@RED@@")
rconsoleprint("Anti-Cheat of the game |Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Use Script|Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Perating Server|Offline." .. " \n")
--//load Anti-Cheat------------------------------------------------------------------------------
wait(0.25)
rconsoleprint(" " .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Loading." .. " \n")
rconsoleprint("Check Anti-Cheat of the game." .. " \n")
rconsoleprint("@@CYAN@@")
wait(1.20)
rconsoleprint("1|100%." .. " \n")
wait(0.20)
rconsoleprint("60|100%." .. " \n")
wait(0.20)
rconsoleprint("81|100%." .. " \n")
wait(0.20)
rconsoleprint("96|100%." .. " \n")
wait(0.20)
rconsoleprint("100|100%." .. " \n")
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-CheatV3." .. " \n")
wait(0.20)
rconsoleprint(" " .. " \n")
rconsoleprint("System." .. " \n")
rconsoleprint("Check Game|Safe." .. " \n")
wait(0.25)
rconsoleprint("Anti-Cheat of the game |Safe." .. " \n")
wait(0.25)
rconsoleprint("@@RED@@")
rconsoleprint("Use Script|Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Perating Server|Offline." .. " \n")
--  Use Script..............................................................................
wait(0.25)
rconsoleprint(" " .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Loading." .. " \n")
rconsoleprint("Check Use Script." .. " \n")
rconsoleprint("@@CYAN@@")
wait(1.20)
rconsoleprint("1|100%." .. " \n")
wait(0.20)
rconsoleprint("45|100%." .. " \n")
wait(0.20)
rconsoleprint("57|100%." .. " \n")
wait(0.20)
rconsoleprint("62|100%." .. " \n")
wait(0.20)
rconsoleprint("79|100%." .. " \n")
wait(0.20)
rconsoleprint("97|100%." .. " \n")
wait(0.20)
rconsoleprint("100|100%." .. " \n")
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-CheatV3." .. " \n")
wait(0.20)
rconsoleprint(" " .. " \n")
rconsoleprint("System." .. " \n")
rconsoleprint("Check Game|Safe." .. " \n")
wait(0.25)
rconsoleprint("Anti-Cheat of the game |Safe." .. " \n")
wait(0.25)
rconsoleprint("Use Script|Safe." .. " \n")
wait(0.25)
rconsoleprint("@@RED@@")
rconsoleprint("Perating Server|Offline." .. " \n")
--..oPerating Server............................................................................
wait(0.25)
rconsoleprint(" " .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Connect." .. " \n")
rconsoleprint("Perating Server." .. " \n")
rconsoleprint("@@CYAN@@")
wait(1.20)
rconsoleprint("1|100%." .. " \n")
wait(0.20)
rconsoleprint("36|100%." .. " \n")
wait(0.20)
rconsoleprint("75|100%." .. " \n")
wait(0.20)
rconsoleprint("97|100%." .. " \n")
wait(0.20)
rconsoleprint("100|100%." .. " \n")
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-CheatV3." .. " \n")
wait(0.20)
rconsoleprint(" " .. " \n")
rconsoleprint("System." .. " \n")
rconsoleprint("Check Game|Safe." .. " \n")
wait(0.25)
rconsoleprint("Anti-Cheat of the game |Safe." .. " \n")
wait(0.25)
rconsoleprint("Use Script|Safe." .. " \n")
wait(0.25)
rconsoleprint("oPerating Server|Online." .. " \n")
rconsoleprint(" " .. " \n")
wait(0.25)
rconsoleprint("Load Dino-Hud." .. " \n")
wait(0.10)
loadstring(game:HttpGetAsync(("https://raw.githubusercontent.com/hovuongphu/Dino-Hud/main/laucher/introl.lua")))()
]]
--[[

rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
wait(0.55)
rconsoleprint(" " .. " \n")
rconsoleprint("System." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Check Game|0/100-Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Anti-Cheat of the game |0/100-Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Use Script|0/100-Not Safe." .. " \n")
wait(0.25)
rconsoleprint("Perating Server|0/100-Offline." .. " \n")
wait(0.25)
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
rconsoleprint(" " .. " \n")
rconsoleprint("@@CYAN@@")
rconsoleprint("System." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Check Game|1/100-Not Safe." .. " \n")
rconsoleprint("Anti-Cheat of the game |1/100-Not Safe." .. " \n")
rconsoleprint("Use Script|1/100-Not Safe." .. " \n")
rconsoleprint("Perating Server|1/100-Offline." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Dino Hud|Connect." .. " \n")
wait(0.25)
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
rconsoleprint(" " .. " \n")
rconsoleprint("@@CYAN@@")
rconsoleprint("System." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Check Game|20/100-Not Safe." .. " \n")
rconsoleprint("Anti-Cheat of the game |3/100-Not Safe." .. " \n")
rconsoleprint("Use Script|7/100-Not Safe." .. " \n")
rconsoleprint("Perating Server|32/100-Offline." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Dino Hud|Connect." .. " \n")
wait(0.25)
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
rconsoleprint(" " .. " \n")
rconsoleprint("@@CYAN@@")
rconsoleprint("System." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Check Game|24/100-Not Safe." .. " \n")
rconsoleprint("Anti-Cheat of the game |12/100-Not Safe." .. " \n")
rconsoleprint("Use Script|11/100-Not Safe." .. " \n")
rconsoleprint("Perating Server|39/100-Offline." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Dino Hud|Connect." .. " \n")
wait(0.25)
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
rconsoleprint(" " .. " \n")
rconsoleprint("@@CYAN@@")
rconsoleprint("System." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Check Game|32/100-Not Safe." .. " \n")
rconsoleprint("Anti-Cheat of the game |26/100-Not Safe." .. " \n")
rconsoleprint("Use Script|17/100-Not Safe." .. " \n")
rconsoleprint("Perating Server|42/100-Offline." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Dino Hud|Connect." .. " \n")
wait(0.25)
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
rconsoleprint(" " .. " \n")
rconsoleprint("@@CYAN@@")
rconsoleprint("System." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Check Game|37/100-Not Safe." .. " \n")
rconsoleprint("Anti-Cheat of the game |35/100-Not Safe." .. " \n")
rconsoleprint("Use Script|28/100-Not Safe." .. " \n")
rconsoleprint("Perating Server|53/100-Offline." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Dino Hud|Connect." .. " \n")
wait(0.25)
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
rconsoleprint(" " .. " \n")
rconsoleprint("@@CYAN@@")
rconsoleprint("System." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Check Game|46/100-Not Safe." .. " \n")
rconsoleprint("Anti-Cheat of the game |48/100-Not Safe." .. " \n")
rconsoleprint("Use Script|37/100-Not Safe." .. " \n")
rconsoleprint("Perating Server|69/100-Offline." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Dino Hud|Connect." .. " \n")
wait(0.25)
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
rconsoleprint(" " .. " \n")
rconsoleprint("@@CYAN@@")
rconsoleprint("System." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Check Game|50/100-Not Safe." .. " \n")
rconsoleprint("Anti-Cheat of the game |56/100-Not Safe." .. " \n")
rconsoleprint("Use Script|44/100-Not Safe." .. " \n")
rconsoleprint("Perating Server|73/100-Offline." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Dino Hud|Connect." .. " \n")
wait(0.25)
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
rconsoleprint(" " .. " \n")
rconsoleprint("@@CYAN@@")
rconsoleprint("System." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Check Game|68/100-Not Safe." .. " \n")
rconsoleprint("Anti-Cheat of the game |65/100-Not Safe." .. " \n")
rconsoleprint("Use Script|50/100-Not Safe." .. " \n")
rconsoleprint("Perating Server|89/100-Offline." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Dino Hud|Connect." .. " \n")
wait(0.25)
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
rconsoleprint(" " .. " \n")
rconsoleprint("@@CYAN@@")
rconsoleprint("System." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Check Game|75/100-Not Safe." .. " \n")
rconsoleprint("Anti-Cheat of the game |78/100-Not Safe." .. " \n")
rconsoleprint("Use Script|62/100-Not Safe." .. " \n")
rconsoleprint("Perating Server|91/100-Offline." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Dino Hud|Connect." .. " \n")
wait(0.25)
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
rconsoleprint(" " .. " \n")
rconsoleprint("@@CYAN@@")
rconsoleprint("System." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Check Game|86/100-Not Safe." .. " \n")
rconsoleprint("Anti-Cheat of the game |82/100-Not Safe." .. " \n")
rconsoleprint("Use Script|70/100-Not Safe." .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Perating Server|100/100-Offline." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Dino Hud|Connect." .. " \n")
wait(0.25)
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
rconsoleprint(" " .. " \n")
rconsoleprint("@@CYAN@@")
rconsoleprint("System." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Check Game|94/100-Not Safe." .. " \n")
rconsoleprint("Anti-Cheat of the game |96/100-Not Safe." .. " \n")
rconsoleprint("Use Script|83/100-Not Safe." .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Perating Server|100/100-Offline." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Dino Hud|Connect." .. " \n")
wait(0.25)
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
rconsoleprint(" " .. " \n")
rconsoleprint("@@CYAN@@")
rconsoleprint("System." .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Check Game|100/100-Not Safe." .. " \n")
rconsoleprint("Anti-Cheat of the game |100/100-Not Safe." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Use Script|70/100-Not Safe." .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Perating Server|100/100-Offline." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Dino Hud|Connect." .. " \n")
wait(0.25)
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
rconsoleprint(" " .. " \n")
rconsoleprint("@@CYAN@@")
rconsoleprint("System." .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Check Game|100/100-Not Safe." .. " \n")
rconsoleprint("Anti-Cheat of the game |100/100-Not Safe." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Use Script|92/100-Not Safe." .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Perating Server|100/100-Offline." .. " \n")
rconsoleprint("@@RED@@")
rconsoleprint("Dino Hud|Connect." .. " \n")
wait(0.25)
rconsoleclear()
rconsoleprint("@@GREEN@@")
rconsoleprint("Create:DINO#5485." .. " \n")
rconsoleprint("Anti-Cheat V3." .. " \n")
rconsoleprint(" " .. " \n")
rconsoleprint("@@CYAN@@")
rconsoleprint("System." .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Check Game|100/100-Not Safe." .. " \n")
rconsoleprint("Anti-Cheat of the game |100/100-Not Safe." .. " \n")
rconsoleprint("Use Script|100/100-Not Safe." .. " \n")
rconsoleprint("Perating Server|100/100-Offline." .. " \n")
rconsoleprint("Dino Hud|Connect." .. " \n")
wait(0.35)
rconsoleprint(" " .. " \n")
rconsoleprint("@@GREEN@@")
rconsoleprint("complete.." .. " \n")







]]



