rconsoleprint("Run File Boot." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
rconsoleprint("Version:V2." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(3)
rconsoleprint("Check Game." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(5)
rconsoleprint("1%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("16%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("35%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("46%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("53%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("71%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("85%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("91%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(3)
rconsoleprint("100%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("Attack Anti Cheat" .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(5)
rconsoleprint("1%" .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("28%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(2)
rconsoleprint("38%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("49%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("55%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("76%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(2)
rconsoleprint("83%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("94%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(2)
rconsoleprint("98%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(2)
rconsoleprint("100%." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("Check Dino Hud." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(1)
rconsoleprint("Not Be Cracked." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
rconsoleprint("Safe, Wait To Run." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(3)
rconsoleprint("Completed." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
rconsoleprint("Create:DINO#5485." .. "["..os.date("%H"..":".."%M"..":".."%S").."]" .. " \n")
wait(3)
loadstring(game:HttpGetAsync(("https://raw.githubusercontent.com/hovuongphu/Dino-Hud/main/laucher/introl.lua")))()