rconsolename('Dino Hud')
rconsoleclear()
rconsoleinfo("Dino Hud")
rconsoleinfo("Create:DINO#5485")
wait(1)
rconsoleprint(" " .. " \n")
rconsolewarn("Scanning user on the system!")
wait(1.50)
loadstring(game:HttpGetAsync(("https://raw.githubusercontent.com/hovuongphu/Dino-Hud/main/ScripMiX/Adminhackallgame.lua")))()

